<?
define("HIDE_SIDEBAR", true);
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle(GetMessage('BASK'));


$APPLICATION->IncludeComponent(
    "bitrix:sale.basket.basket",
    "basket",
    array(
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "COLUMNS_LIST" => array(
            0 => "NAME",
            1 => "DISCOUNT",
            2 => "PRICE",
            3 => "QUANTITY",
            4 => "SUM",
            5 => "PROPS",
            6 => "DELETE",
            7 => "DELAY",
        ),
        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
        "HIDE_COUPON" => "Y",
        "OFFERS_PROPS" => array(
            0 => "ART",
        ),
        "PATH_TO_ORDER" => "/personal/order/make/",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "QUANTITY_FLOAT" => "N",
        "SET_TITLE" => "Y",
        "TEMPLATE_THEME" => "",
        "COMPONENT_TEMPLATE" => "basket",
        "DEFERRED_REFRESH" => "N",
        "USE_DYNAMIC_SCROLL" => "Y",
        "SHOW_FILTER" => "Y",
        "SHOW_RESTORE" => "N",
        "COLUMNS_LIST_EXT" => array(
            0 => "PREVIEW_PICTURE",
            1 => "DETAIL_PICTURE",
            2 => "PREVIEW_TEXT",
            3 => "DISCOUNT",
            4 => "PROPS",
            5 => "DELETE",
            6 => "DELAY",
            7 => "PROPERTY_SHORT_TEXT",
            8 => "PROPERTY_CATALOGTITLE",
            9 => "PROPERTY_ARTICUL",
            10 => "PROPERTY_MATERIAL",
        ),
        "COLUMNS_LIST_MOBILE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "DETAIL_PICTURE",
            2 => "PREVIEW_TEXT",
            3 => "DISCOUNT",
            4 => "PROPS",
            5 => "DELETE",
            6 => "DELAY",
            7 => "PROPERTY_CATALOGTITLE",
            8 => "PROPERTY_ARTICUL",
            9 => "PROPERTY_MATERIAL",
        ),
        "TOTAL_BLOCK_DISPLAY" => array(
            0 => "top",
        ),
        "DISPLAY_MODE" => "extended",
        "PRICE_DISPLAY_MODE" => "N",
        "SHOW_DISCOUNT_PERCENT" => "N",
        "PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
        "USE_PRICE_ANIMATION" => "N",
        "LABEL_PROP" => array(),
        "USE_PREPAYMENT" => "N",
        "CORRECT_RATIO" => "Y",
        "AUTO_CALCULATION" => "Y",
        "ACTION_VARIABLE" => "basketAction",
        "COMPATIBLE_MODE" => "Y",
        "LABEL_PROP_MOBILE" => "",
        "LABEL_PROP_POSITION" => "",
        "ADDITIONAL_PICT_PROP_11" => "-",
        "BASKET_IMAGES_SCALING" => "adaptive",
        "USE_GIFTS" => "N",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "ADDITIONAL_PICT_PROP_19" => "-"
    ),
    false
); ?><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>